spring:
  application:
    name: rydo-common
jwt:
  secret: YOUR-256-BIT-SECRET-YOU-MUST-KEEP-SAME-AS-USER-SERVICE
  expirationMs: 7200000 # 1000 * 60 * 60 * 2 # 10 hours
ride:
  service:
    radius: 60000